Support forward references in `ProtoStruct`
LagrangeDev/lagrange-python pull request #19
Opened 2024-08-14 01:25 UTC by pk5ls20

Now you can using forward references in ProtoStruct class, like below:
```python
class OidbFriend(ProtoStruct):
    uid: str = proto_field(1)
    custom_group: Optional[int] = proto_field(2, default=None)
    uin: int = proto_field(3)
    additional: list["OidbFriendAdditional"] = proto_field(10001)

class OidbFriendAdditional(ProtoStruct):
    type: int = proto_field(1)
    layer1: "OidbFriendLayer1" = proto_field(2, default=None)

class OidbFriendProperty(ProtoStruct):
    code: Optional[int] = proto_field(1)
    value: Optional[str] = proto_field(2)

class OidbFriendLayer1(ProtoStruct):
    properties: Optional[list[OidbFriendProperty]] = proto_field(2, default=None)
```

2024-08-14 11:22 UTC, pk5ls20 commented
先别合（

2024-08-14 11:44 UTC, pk5ls20 commented
应该没问题了.jpg

2024-08-15 03:31 UTC, RF-Tar-Railt commented
？forwardref直接用它自己的_evaluate就行了啊

2024-08-15 06:51 UTC, pk5ls20 commented
@RF-Tar-Railt 能再帮着看下嘛，感谢

2024-08-15 07:32 UTC, RF-Tar-Railt commented
我不确定靠导入模块拿globals的行为是否可靠，相比通过frame查找。。。

这块或许还得看看pydanticV1是怎么做的

2024-08-15 07:42 UTC, pk5ls20 commented
> 我不确定靠导入模块拿globals的行为是否可靠，相比通过frame查找。。。
> 
> 这块或许还得看看pydanticV1是怎么做的

这样写的话应该单文件内的前向引用都没有问题吧🤔

2024-08-15 08:26 UTC, RF-Tar-Railt requested changes

2024-08-15 08:26 UTC, RF-Tar-Railt commented on lagrange/utils/binary/protobuf/models.py
> +        local = importlib.import_module(arg.__module__).__dict__
这一块可以加一段先从 sys.modules 找模块：

```python
if globalns is None:
    base_globals = sys.modules[base.__module__].__dict__
else:
    base_globals = globalns
```

2024-08-15 08:26 UTC, RF-Tar-Railt commented on lagrange/utils/binary/protobuf/models.py
另外我感觉整个annotations的实现都得改一下，多利用typing里现有的东西（例如 get_type_hints 之类的）

2024-08-15 15:34 UTC, wyapx commented on lagrange/utils/binary/protobuf/models.py
纯typing不太好弄的样子，暴露的接口太少

2024-09-24 18:41 UTC, wyapx commented
fix on #36

2024-09-24 18:41 UTC, closed without merging