feat(event): FriendRequest
LagrangeDev/lagrange-python pull request #38
Opened 2024-09-26 16:20 UTC by HornCopper

2024-09-27 04:55 UTC, pk5ls20 requested changes

2024-09-27 04:55 UTC, pk5ls20 commented on lagrange/client/server_push/msg.py
> +            try:
用判断是否为空完成这段逻辑

2024-09-28 10:21 UTC, wyapx requested changes

2024-09-28 10:21 UTC, wyapx commented on lagrange/pb/status/friend.py
> +    verify: str = proto_field(10) # 验证消息：我是...
```suggestion
    verify: str = proto_field(10)  # 验证消息：我是...
```
pep8...

2024-09-28 10:21 UTC, wyapx commented on lagrange/client/server_push/msg.py
> +            except KeyError: # 空包wdnmd
不要使用try进行空判断，没有意义

2024-09-28 21:16 UTC, HornCopper commented on lagrange/client/server_push/msg.py
> +            try:
似乎这个sub_type对应的包有可能是个不具备任何有意义数据的包，用`PBFriendRequest`无法解析，但并不是完全空包

2024-09-28 21:16 UTC, HornCopper commented on lagrange/client/server_push/msg.py
> +            except KeyError: # 空包wdnmd
参考上方

2024-10-09 17:02 UTC, pk5ls20 approved these changes

2024-10-09 17:02 UTC, merged